[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "pytensorforge"
version = "0.1.2"
description = "Deep Learning Framework"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Nnamdi Chidume" }]
license = "MIT"
license-files = ["LICENSE"]
dependencies = ["numpy>=1.24", "pyyaml>=6.0"]

[project.urls]
Homepage = "https://github.com/philipszdavido/pytensorforge"
Repository = "https://github.com/philipszdavido/pytensorforge"

[tool.setuptools.packages.find]
include = ["pytensorforge*"]